import Head from 'next/head'
import { Inter } from 'next/font/google'

import { SSRProvider } from 'react-bootstrap'
import { Container } from 'react-bootstrap'
import UITableView from './UITableView'
import Task, { TaskState } from "../Task"

const exampleData = new Map([
    ['Выполненные задачи', [new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date())]],
    ['Задачи на сегодня', [new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date())]],
    [/* repeat this array 4 times more */'Предстоящие задачи', [new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date()), new Task(new Date(), "Шифр задачи", "48/21", "Прозвонить Копьева", TaskState.done, "Иванова В. А.", "Свердлова А. И.", "2", "Комментарий", new Date(), new Date(), new Date(), new Date())]]
])

export default function Home() {
    return (
        <SSRProvider>
            <Head>
                <title>Tasks</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <UITableView tasks={exampleData} />
        </SSRProvider>
    )
}
