name: Authentication
run-name: ${{ github.actor }} deploys via GitHub Actions

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Authentication/
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            - run: mkdir ../_site/
            - run: mv * ../_site/
            - uses: actions/upload-pages-artifact@v2

    deploy:
        needs: build
        runs-on: ubuntu-latest

        # What does this do?
        permissions:
            id-token: write
            pages: write

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2
