name: Bad
run-name: ${{ github.actor }} deploys via GitHub Actions

on:
  workflow_dispatch:
    inputs:
      path:
        description: A folder containing a package.json file.
        required: false
        default: 'nil'
        type: string

jobs:
  commit-package-lock-json-if-specified:
    runs-on: ubuntu-latest
    name: Commit package-lock.json

    if: ${{ !contains(inputs.path, 'nil') }}
    steps:
      - uses: actions/checkout@v4

      - name: Get package-lock.json
        run: npm install
        working-directory: ${{ inputs.path }}
      - run: mv package-lock.json ..

      - uses: EndBug/add-and-commit@v9.1.3
        with:
          add: package-lock.json

  build-all:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: commit-package-lock-json-if-specified
    name: Build All

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3

      - run: mkdir -v _site
      - run: |
          mkdir -v \
          _r__-for-a-comment \
          cru_-for-an-application \
          crud-for-a-x \
          just-a-card \
          just-a-form \
          x \
          # yandex-disk
        working-directory: _site

# _R__ for a Comment
      - run: npm ci
        working-directory: Message Fetcher/
      - name: Build “Message Fetcher”
        run: npm run build
        working-directory: Message Fetcher/

# CRUD for a X
      - run: mv javascript/дипломная_работа/index.html _site/crud-for-a-x

# CRU_ for an Application
      - run: npm ci
        working-directory: cru_-for-an-application
      - name: Buid
        run: npm run build:release
        working-directory: cru_-for-an-application

# Just a Card
      - run: npm ci
        working-directory: just-a-card/
      - name: Build “Just a Card”
        run: npm run build
        working-directory: just-a-card/

# Just a Form
      - run: mv just-a-form/* _site/just-a-form

# X
      - run: npm ci
        working-directory: Next.js/x
      - name: Build “X”
        run: npm run build
        working-directory: Next.js/x

      - run: mv cru_-for-an-application/.build/* _site/cru_-for-an-application
      - run: mv Card/dist/* _site/just-a-card/
      - run: mv Next.js/proportional/out/* _site/x
      - run: mv Message\ Fetcher/build/* _site/_r__-for-a-comment/

      - uses: actions/upload-pages-artifact@v2

  #test-all:
    #runs-on: ubuntu-latest
    #steps:

  deploy-all:
    runs-on: ubuntu-latest
    needs: build-all
    name: Deploy All

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
