name: Bad
run-name: ${{ github.actor }} deploys via GitHub Actions

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: git clone
              uses: actions/checkout@v4

            - uses: actions/setup-node@v3

            - run: mkdir _site
            - run: mkdir _site/message-fetcher
            - run: mkdir _site/authentication
            - run: mkdir _site/applications
            - run: mkdir _site/proportional
            - run: mkdir _site/card
            - run: mkdir _site/graduate-work # Initially Modified: 07:46 PM Mon 06 Nov 2023
                                             #      Last Modified: 07:50 PM Mon 06 Nov 2023

            # Graduate Work
            - run: mv javascript/дипломная_работа/index.html _site/graduate-work

            # Card
            - run: npm ci
              working-directory: Card/
            - name: Build “Card”
              run: npm run build
              working-directory: Card/
            - run: mv Card/dist/* _site/card/

            # Message Fetcher
            - run: npm ci
              working-directory: Message Fetcher/
            - name: Build “Message Fetcher”
              run: npm run build
              working-directory: Message Fetcher/
            - run: mv Message\ Fetcher/build/* _site/message-fetcher/

            # Authentication
            - run: mv Authentication/* _site/authentication

            # Applications
            - run: mv html_css_js/тестовое_задание_0/* _site/applications

            # Proportional
            - run: npm ci
              working-directory: Next.js/proportional
            - name: Build “Proportional”
              run: npm run build
              working-directory: Next.js/proportional

            - run: mv Next.js/proportional/out/* _site/proportional

            - uses: actions/upload-pages-artifact@v2
    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            pages: write
            
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2
