name: GitHub Pages
run-name: ${{ github.actor }} ran GitHub Pages

on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # It does not make sense to upload this repository as an artifact but I have to because I do not want it to be cloned as many times as the next job needs.
      - uses: actions/upload-artifact@v4
        with:
          name: shared
          path: |
            **/*
            !**/script/**/*
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        package: ${{ fromJSON(inputs.json) }}
      fail-fast: false

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: shared
      - uses: actions/setup-node@v4
      - run: mkdir -p _site/
      - run: ${{ matrix.package.prepare }}

      - run: ${{ matrix.package.prebuild }} # For example: npm install-clean
        working-directory: ${{ matrix.package.directory }}
      - run: ${{ matrix.package.build }} # For example: npm run-script build
        working-directory: ${{ matrix.package.directory }}
      - run: ${{ matrix.package.postbuild }} # For example: mv directory/.build/* _site/directory/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package.directory }}
          path: _site/*

  boilerplate:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .

      - run: rsync -a --remove-source-files ./Documentation/* . # Thanks to Copilot :) I hope it now works :/
      - run: tar --exclude='./shared' -cf artifact.tar ./*

      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar

  deploy:
    needs: boilerplate
    uses: ./.github/workflows/deploy.yaml
    permissions:
      id-token: write
      pages: write
