name: GitHub Pages
run-name: ${{ github.actor }} ran GitHub Pages
on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string
      runs-on:
        required: false
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - windows-latest
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3 # It does not make sense to upload this repository as an artifact but I have to because I do not want my repository to be cloned as many times as this workflow needs.
        with:
          name: repository
          path: .
          retention-days: 1
  build:
    runs-on: ${{ inputs.runs-on }}
    needs: checkout
    strategy:
      matrix:
        package: ${{ fromJSON(inputs.json) }}
      fail-fast: false

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: repository
      - uses: actions/setup-node@v3
      - run: mkdir -p _site/${{ matrix.package.directory }}/

      - run: ${{ matrix.package.prebuild }} # For example: npm install-clean
        working-directory: ${{ matrix.package.directory }}
      - run: ${{ matrix.package.build }} # For example: npm run-script build
        working-directory: ${{ matrix.package.directory }}
      - run: ${{ matrix.package.postbuild }} # For example: mv directory/.build/* _site/directory/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package.directory }}
          path: _site/**/*

  boilerplate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: .

      - run: tar -cf -X=repository artifact.tar ./*

      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar

  deploy:
    runs-on: ubuntu-latest
    needs: boilerplate
    steps:
      - uses: actions/deploy-pages@v2

    permissions:
      id-token: write
      pages: write
