name: GitHub Pages
run-name: ${{ github.actor }} ran GitHub Pages

on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string

jobs:
  # in:4:42 PM...4:48 PM Sun 14 Jan 2024
  weird-github-job:
    runs-on: ubuntu-latest
    outputs: # 4:35 PM...4:37 PM Sun 14 Jan 2024
      sparse-checkout: ${{ steps.interpolate.outputs.value }}

    steps:
      # 4:34 PM...4:41 PM Sun 14 Jan 2024
      - run: echo -e "value=${{ join(fromJson(inputs.json).*.directory, '\n') }}" >> "$GITHUB_OUTPUT"
        id: interpolate

  checkout:
    runs-on: ubuntu-latest
    needs: weird-github-job
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ needs.weird-github-job.outputs.sparse-checkout }}
      - uses: actions/upload-artifact@v4 # It does not make sense to upload this repository as an artifact but I have to because I do not want it to be cloned as many times as the next job needs.
        with:
          name: shared
          path: .
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        package: ${{ fromJSON(inputs.json) }}
      fail-fast: false

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: shared
      - uses: actions/setup-node@v4
      - run: mkdir -p _site/

      - run: ${{ matrix.package.prebuild }} # For example: npm install-clean
        working-directory: ${{ matrix.package.directory }}
      - run: ${{ matrix.package.build }} # For example: npm run-script build
        working-directory: ${{ matrix.package.directory }}
      - run: ${{ matrix.package.postbuild }} # For example: mv directory/.build/* _site/directory/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package.directory }}
          path: _site/*

  boilerplate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .

      - run: tar --exclude='./repository' -cf artifact.tar ./*

      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./artifact.tar

  deploy:
    needs: boilerplate
    uses: ./.github/workflows/deploy.yaml
    permissions:
      id-token: write
      pages: write
